# Generated by Django 4.2.7 on 2023-12-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_cart_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='botadmin',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
